env:
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style: off
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-control-regex: off # allow control character matching in regex